# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# batch_define_raster_projection.py
# Created on: 2019-05-16 15:21:53.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: batch_define_raster_projection <Coordinate_System> <Input_Raster_Directory> <Wildcard> <Raster_Format> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("Model Functions")

# Script arguments
Coordinate_System = arcpy.GetParameterAsText(0)

Input_Raster_Directory = arcpy.GetParameterAsText(1)

Wildcard = arcpy.GetParameterAsText(2)

Raster_Format = arcpy.GetParameterAsText(3)

# Local variables:
Name = Wildcard
Input_Raster = "\\Raster"
Output_Raster = Input_Raster

# Process: Iterate Rasters
arcpy.IterateRasters_mb(Input_Raster_Directory, Wildcard, Raster_Format, "NOT_RECURSIVE")

# Process: Define Projection
arcpy.DefineProjection_management(Input_Raster, Coordinate_System)

