# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# error_patch_generation.py
# Created on: 2019-05-16 15:16:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: error_patch_generation <Error_Polygon_Shapefile> <Project_Tile_Layout> <Buffer_Distance> <Aggregation_Distance> <Patch_Field_Expression__Default__FID_> <Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__> <Final_Error_Patch_Shapefile__ex_P__Projects_Your_Project_Ortho_QC_Shapes_Error_Patch_shp_> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("P:/ADS/Custom_Tools.tbx")

# Script arguments
Error_Polygon_Shapefile = arcpy.GetParameterAsText(0)

Project_Tile_Layout = arcpy.GetParameterAsText(1)

Buffer_Distance = arcpy.GetParameterAsText(2)
if Buffer_Distance == '#' or not Buffer_Distance:
    Buffer_Distance = "200 Meters" # provide a default value if unspecified

Aggregation_Distance = arcpy.GetParameterAsText(3)
if Aggregation_Distance == '#' or not Aggregation_Distance:
    Aggregation_Distance = "50 Meters" # provide a default value if unspecified

Patch_Field_Expression__Default__FID_ = arcpy.GetParameterAsText(4)
if Patch_Field_Expression__Default__FID_ == '#' or not Patch_Field_Expression__Default__FID_:
    Patch_Field_Expression__Default__FID_ = "[FID]" # provide a default value if unspecified

Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__ = arcpy.GetParameterAsText(5)
if Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__ == '#' or not Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__:
    Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__ = "\"\"" # provide a default value if unspecified

Final_Error_Patch_Shapefile__ex_P__Projects_Your_Project_Ortho_QC_Shapes_Error_Patch_shp_ = arcpy.GetParameterAsText(6)

# Local variables:
Output_Feature_Class = ""
Output_Feature_Class__2_ = ""
Output_Table = ""
Output_Feature_Class__3_ = ""
TEMP_Shapefile_Name_Location = "C:\\Temp\\temp_error_tif.shp"
Output_Feature_Class__4_ = TEMP_Shapefile_Name_Location
Output_Feature_Class__5_ = Output_Feature_Class__4_
temp_error_tif_shp = Output_Feature_Class__5_
Output_Feature_Class__7_ = temp_error_tif_shp
temp_error_tif_shp__2_ = Output_Feature_Class__7_
temp_error_tif_shp__3_ = temp_error_tif_shp__2_
Output_Table__3_ = temp_error_tif_shp__3_
Delete_succeeded = "false"

# Process: Feature Envelope To Polygon
arcpy.FeatureEnvelopeToPolygon_management(Error_Polygon_Shapefile, Output_Feature_Class, "SINGLEPART")

# Process: Buffer
arcpy.Buffer_analysis(Output_Feature_Class, Output_Feature_Class__2_, Buffer_Distance, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Aggregate Polygons
arcpy.AggregatePolygons_cartography(Output_Feature_Class__2_, Output_Feature_Class__3_, Aggregation_Distance, "0 SquareMeters", "0 SquareMeters", "NON_ORTHOGONAL", "", Output_Table)

# Process: Feature Envelope To Polygon (2)
arcpy.FeatureEnvelopeToPolygon_management(Output_Feature_Class__3_, TEMP_Shapefile_Name_Location, "SINGLEPART")

# Process: Add Field
arcpy.AddField_management(TEMP_Shapefile_Name_Location, "PID", "TEXT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field
arcpy.CalculateField_management(Output_Feature_Class__4_, "PID", Patch_Field_Expression__Default__FID_, "VB", "")

# Process: Add Field (2)
arcpy.AddField_management(Output_Feature_Class__5_, "Patch_Path", "TEXT", "", "", "200", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (2)
arcpy.CalculateField_management(temp_error_tif_shp, "Patch_Path", Error_Patch_TIF_Folder_in_Quotes__ex___S__ORTHO_29909_PEMA_Bucks_Error_Patch_TIFs__, "VB", "")

# Process: Add Field (3)
arcpy.AddField_management(Output_Feature_Class__7_, "Error_Path", "TEXT", "", "", "200", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Calculate Field (3)
arcpy.CalculateField_management(temp_error_tif_shp__2_, "Error_Path", "[Patch_Path]&\"\\\"&[PID]&\".tif\"", "VB", "")

# Process: Delete Field (2)
arcpy.DeleteField_management(temp_error_tif_shp__3_, "Patch_Path;Shape_Leng;Shape_Area;ORIG_FID")

# Process: Spatial Join (2)
arcpy.gp.toolbox = "P:/ADS/Custom_Tools.tbx";
# Warning: the toolbox P:/ADS/Custom_Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.SpatialJoin(...) with arcpy.SpatialJoin_ALIAS(...)
arcpy.gp.SpatialJoin(TEMP_Shapefile_Name_Location, Project_Tile_Layout, Final_Error_Patch_Shapefile__ex_P__Projects_Your_Project_Ortho_QC_Shapes_Error_Patch_shp_)

# Process: Delete
arcpy.Delete_management(TEMP_Shapefile_Name_Location, "")

