# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# flat_patch_generation.py
# Created on: 2019-05-16 15:23:43.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: flat_patch_generation <Error_Polygon_Shapefile> <Buffer_Distance> <Aggregation_Distance> <Output_Shapefile_Name_Location> <Patch_Field_Expression__Default__FID_> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy

# Script arguments
Error_Polygon_Shapefile = arcpy.GetParameterAsText(0)

Buffer_Distance = arcpy.GetParameterAsText(1)
if Buffer_Distance == '#' or not Buffer_Distance:
    Buffer_Distance = "200 Meters" # provide a default value if unspecified

Aggregation_Distance = arcpy.GetParameterAsText(2)
if Aggregation_Distance == '#' or not Aggregation_Distance:
    Aggregation_Distance = "50 Meters" # provide a default value if unspecified

Output_Shapefile_Name_Location = arcpy.GetParameterAsText(3)

Patch_Field_Expression__Default__FID_ = arcpy.GetParameterAsText(4)
if Patch_Field_Expression__Default__FID_ == '#' or not Patch_Field_Expression__Default__FID_:
    Patch_Field_Expression__Default__FID_ = "[FID]" # provide a default value if unspecified

# Local variables:
Output_Feature_Class = ""
Output_Feature_Class__2_ = ""
Output_Table = ""
Output_Feature_Class__3_ = ""
Output_Feature_Class__4_ = Output_Shapefile_Name_Location
Output_Table__2_ = Output_Feature_Class__4_
Drop_Field = "Shape_Leng;Shape_Area;ORIG_FID"
Output_Feature_Class__5_ = Output_Table__2_

# Process: Feature Envelope To Polygon
arcpy.FeatureEnvelopeToPolygon_management(Error_Polygon_Shapefile, Output_Feature_Class, "SINGLEPART")

# Process: Buffer
arcpy.Buffer_analysis(Output_Feature_Class, Output_Feature_Class__2_, Buffer_Distance, "FULL", "ROUND", "NONE", "", "PLANAR")

# Process: Aggregate Polygons
arcpy.AggregatePolygons_cartography(Output_Feature_Class__2_, Output_Feature_Class__3_, Aggregation_Distance, "0 SquareMeters", "0 SquareMeters", "NON_ORTHOGONAL", "", Output_Table)

# Process: Feature Envelope To Polygon (2)
arcpy.FeatureEnvelopeToPolygon_management(Output_Feature_Class__3_, Output_Shapefile_Name_Location, "SINGLEPART")

# Process: Add Field
arcpy.AddField_management(Output_Shapefile_Name_Location, "PID", "SHORT", "", "", "100", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Delete Field
arcpy.DeleteField_management(Output_Feature_Class__4_, Drop_Field)

# Process: Calculate Field
arcpy.CalculateField_management(Output_Table__2_, "PID", Patch_Field_Expression__Default__FID_, "VB", "")

