# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# frame_pt_intersect.py
# Created on: 2019-05-16 15:21:38.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: frame_pt_intersect <Frame_SHP_File> <Control_Pt_Text_File> <X_Field> <Y_Field> <Z_Field> <Spatial_Reference> <Intersected_Pts_Shapefile_Location_Name> <Intersected_Frames_Shapefile_Name> <Intersected_Frames_Shapefile_Location> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Frame_SHP_File = arcpy.GetParameterAsText(0)

Control_Pt_Text_File = arcpy.GetParameterAsText(1)

X_Field = arcpy.GetParameterAsText(2)

Y_Field = arcpy.GetParameterAsText(3)

Z_Field = arcpy.GetParameterAsText(4)

Spatial_Reference = arcpy.GetParameterAsText(5)
if Spatial_Reference == '#' or not Spatial_Reference:
    Spatial_Reference = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;0.001;0.001;IsHighPrecision" # provide a default value if unspecified

Intersected_Pts_Shapefile_Location_Name = arcpy.GetParameterAsText(6)

Intersected_Frames_Shapefile_Name = arcpy.GetParameterAsText(7)

Intersected_Frames_Shapefile_Location = arcpy.GetParameterAsText(8)

# Local variables:
TEMP_Frames = "TEMP_Frames"
TEMP_Frames__3_ = TEMP_Frames
TEMP_Pts = "TEMP_Pts"
TEMP_shp = "c:\\TEMP.shp"
Output_Type = "POINT"
Output_Feature_Class = ""
Delete_succeeded = "false"

# Process: Make Feature Layer
arcpy.MakeFeatureLayer_management(Frame_SHP_File, TEMP_Frames, "", "", "")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(Control_Pt_Text_File, X_Field, Y_Field, TEMP_Pts, Spatial_Reference, Z_Field)

# Process: Feature Class to Feature Class (2)
arcpy.FeatureClassToFeatureClass_conversion(TEMP_Pts, Intersected_Frames_Shapefile_Location, "TEMP.shp", "", "", "")

# Process: Intersect
arcpy.Intersect_analysis("TEMP_Frames #;c:\\TEMP.shp #", Intersected_Pts_Shapefile_Location_Name, "NO_FID", "", Output_Type)

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(TEMP_Frames, "INTERSECT", TEMP_Pts, "", "NEW_SELECTION", "NOT_INVERT")

# Process: Feature Class to Feature Class
arcpy.FeatureClassToFeatureClass_conversion(TEMP_Frames__3_, Intersected_Frames_Shapefile_Location, Intersected_Frames_Shapefile_Name, "", "", "")

# Process: Delete
arcpy.Delete_management(TEMP_shp, "")

