# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# project_setup.py
# Created on: 2019-05-16 15:22:41.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: project_setup <Project_Folder__QC_Folder_Location_> <QC_Folder_Name> <Project_Name_for_GDB> <Coordinate_System> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Load required toolboxes
arcpy.ImportToolbox("P:/ADS/Custom_Tools.tbx")

# Script arguments
Project_Folder__QC_Folder_Location_ = arcpy.GetParameterAsText(0)

QC_Folder_Name = arcpy.GetParameterAsText(1)
if QC_Folder_Name == '#' or not QC_Folder_Name:
    QC_Folder_Name = "QC" # provide a default value if unspecified

Project_Name_for_GDB = arcpy.GetParameterAsText(2)

Coordinate_System = arcpy.GetParameterAsText(3)

# Local variables:
QC_SEED_UTM16 = "P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16"
Output_Feature_Class__2_ = QC_SEED_UTM16
Output_Folder = Project_Folder__QC_Folder_Location_
Output_File_GDB = Output_Folder
Output_Feature_Class__3_ = "QC_SEED"
Feature_Class_Name__2_ = "SEAM_SEED"
Geometry_Type__2_ = "POLYLINE"
Output_Feature_Class = ""
Output_Feature_Class__4_ = Output_Feature_Class

# Process: Create Folder
arcpy.CreateFolder_management(Project_Folder__QC_Folder_Location_, QC_Folder_Name)

# Process: Create File GDB
arcpy.CreateFileGDB_management(Output_Folder, Project_Name_for_GDB, "CURRENT")

# Process: Copy QC Seed
tempEnvironment0 = arcpy.env.outputCoordinateSystem
arcpy.env.outputCoordinateSystem = Coordinate System
arcpy.FeatureClassToFeatureClass_conversion(QC_SEED_UTM16, Output_File_GDB, Output_Feature_Class__3_, "", "TYPE \"TYPE\" true true false 50 Text 0 0 ,First,#,P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16,TYPE,-1,-1;FIX \"FIX\" true true false 50 Text 0 0 ,First,#,P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16,FIX,-1,-1;COMMENT \"COMMENT\" true true false 200 Text 0 0 ,First,#,P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16,COMMENT,-1,-1;SHAPE_Length \"SHAPE_Length\" false true true 8 Double 0 0 ,First,#,P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16,SHAPE_Length,-1,-1;SHAPE_Area \"SHAPE_Area\" false true true 8 Double 0 0 ,First,#,P:\\Projects\\__ArcMap_Master_GDB_LYR\\QC_Master.gdb\\QC_SEED_UTM16,SHAPE_Area,-1,-1", "")
arcpy.env.outputCoordinateSystem = tempEnvironment0

# Process: SEAM_SEED_Creation
arcpy.CreateFeatureclass_management(Output_File_GDB, Feature_Class_Name__2_, Geometry_Type__2_, "", "DISABLED", "DISABLED", Coordinate_System, "", "0", "0", "0")

# Process: Add Field
arcpy.AddField_management(Output_Feature_Class, "RECTS", "TEXT", "", "", "50", "", "NULLABLE", "NON_REQUIRED", "")

# Process: Copy Master MXD
arcpy.gp.toolbox = "P:/ADS/Custom_Tools.tbx";
# Warning: the toolbox P:/ADS/Custom_Tools.tbx DOES NOT have an alias. 
# Please assign this toolbox an alias to avoid tool name collisions
# And replace arcpy.gp.CopyMXD2(...) with arcpy.CopyMXD2_ALIAS(...)
arcpy.gp.CopyMXD2(Output_Folder)

